export const PAPERS = [
  {
    id: "01",
    paperId: "PAPER 01",
    category: "MATH.NT",
    title: "Constitutional Forcing",
    metadata: "11N35 · 11N13 · 94A15 · 76F02",
    status: "PROVED",
    teaser: "The mechanism named. Formal definition. Counting Theorem proved by induction. Four instances across three domains including Kolmogorov's turbulence exponent α = 3/4.",
    essayTitle: "Khayyam's Triangle",
    paperUrl: "/papers/p01",
    essayUrl: "/essays/khayyams-triangle"
  },
  {
    id: "02",
    paperId: "PAPER 02",
    category: "MATH.HO",
    title: "Khayyam's Triangle",
    metadata: "01A30 · 11B65 · 28A80",
    status: "PROVED",
    teaser: "Historical restoration and the combinatorial origin of the cascade framework in the mod-3 Sierpiński fractal.",
    essayTitle: "The Shannon-Wakil Effect",
    paperUrl: "/papers/p02",
    essayUrl: "/essays/the-shannon-wakil-effect"
  },
  {
    id: "03",
    paperId: "PAPER 03",
    category: "MATH.HO",
    title: "Spherical Cow Philosophy",
    metadata: "00A30 · 00A35 · 11N35",
    status: "PROVED",
    teaser: "The methodological framework. Why accepting the constitutional constraint as entry point is non-circular and falsifiable. The Sophie Germain non-instance.",
    essayTitle: "Spherical Cow Philosophy",
    paperUrl: "/papers/p03",
    essayUrl: "/essays/spherical-cow-philosophy"
  },
  {
    id: "04",
    paperId: "PAPER 04",
    category: "MATH.NT",
    title: "Eisenstein Integers, θ = 5/8",
    metadata: "11N13 · 11N35 · 11L05",
    status: "PROVED (UNCONDITIONAL VIA PAPER 07)",
    teaser: "The main arithmetic result. θW = 5/8 for cascade moduli via Eisenstein ramification and Watt's theorem.",
    essayTitle: "Once Upon a Napkin",
    paperUrl: "/papers/p04",
    essayUrl: "/essays/once-upon-a-napkin"
  },
  {
    id: "05",
    paperId: "PAPER 05",
    category: "MATH.NT",
    title: "Ramanujan's Dimensional Forcing",
    metadata: "11N35 · 11N36 · 05A16",
    status: "PROVED · K≥4 CONJECTURAL",
    teaser: "The universal formula θk = (2k − k)/2k. Unifies Bombieri–Vinogradov and Pascadi as special cases. Predicts θ₅ = 27/32.",
    essayTitle: "The Quilt Proof",
    essayTeaser: "The convergence of independent routes to the same tiny island of truth.",
    paperUrl: "/papers/p05",
    essayUrl: "/essays/the-quilt-proof"
  },
  {
    id: "06",
    paperId: "PAPER 06",
    category: "CS.IT / MATH.NT",
    title: "The Shannon–Wakil Effect",
    metadata: "94A15 · 94A24 · 11N35",
    status: "PROVED",
    teaser: "Five structural correspondences between Shannon's 1948 theorems and the cascade moduli arithmetic. The 77-year gap.",
    essayTitle: "The Stepping Stones",
    essayTeaser: "The cascade of constraints that forced the ternary architecture and the proof of Condition W3.",
    paperUrl: "/papers/p06",
    essayUrl: "/essays/the-stepping-stones"
  },
  {
    id: "07",
    paperId: "PAPER 07",
    category: "MATH.NT",
    title: "Condition W3",
    metadata: "11M20 · 11R42 · 11N13",
    status: "PROVED (UNCONDITIONAL)",
    teaser: "The foundation proof. No Siegel zeros for characters modulo 3K via the CM field Q(ω). The same Eisenstein structure does both jobs: forces θ = 5/8 and prevents the zeros that would undermine it.",
    essayTitle: "The Seventh Domain",
    essayTeaser: "Constitutional Forcing was not invented in 2026. It was recognized. That is a different thing, and the difference matters.",
    paperUrl: "/papers/p07",
    essayUrl: "/essays/the-seventh-domain"
  },
  {
    id: "08",
    paperId: "PAPER 08",
    category: "MATH.NT",
    title: "Prime Digit Bias Explained",
    metadata: "11N05 · 11N13 · 11A41",
    status: "PROVED",
    teaser: "The unbidden result. Nine years of \"deeply unsettling.\" Dissolved.",
    essayTitle: "The Sustained Note",
    essayTeaser: "The framework became generative. That is the thing nobody tells you about naming a mechanism: once it has a name, it starts finding its own instances.",
    paperUrl: "/papers/p08",
    essayUrl: "/essays/the-sustained-note"
  },
  {
    id: "09",
    paperId: "PAPER 09",
    category: "CS.IT / MATH.CA",
    title: "The DFT Constitutional Constant",
    metadata: "42A38 · 94A12 · 28A80",
    status: "PROVED · 6TH INSTANCE NAMED",
    teaser: "Formal proof, empirical confirmation, bridge to Khayyam's Triangle. The cleanest instance. Two lines. Sixty years implicit. Named 2026.",
    essayTitle: "Domain-ation",
    essayTeaser: "θ_FFT = 1/2 is Bombieri-Vinogradov in the frequency domain. Same depth. Same formula. Different domain. Different century. Same forced constant.",
    paperUrl: "/papers/p09",
    essayUrl: "/essays/domain-ation"
  },
];
